KLab/wsnet2

server/go.mod

update go version in go.mod

---

server/cmd/wsnet2-tool/cmd/oldrooms.go
server/cmd/wsnet2-tool/cmd/rooms.go
server/cmd/wsnet2-tool/cmd/rooms_test.go

- rooms/oldroomsのプロパティ表示
- jsonでパース可能に
- 要素数の少ない配列は中身を表示
- oldroomsにオプション追加
- createdのbefore/after

Enhancement of wsnet2-tool

---

wsnet2-dotnet/WSNet2.Core.Test/WSNet2.Core.Test.csproj

client: Use net6.0 as target framework for test project

---

server/game/peer.go
wsnet2-unity/Assets/WSNet2/Scripts/Core/Connection.cs

書き込みが詰まるとClientのEventLoopが止まってしまい、再接続してもEventが流れてこなくなっていました。
毎回Deadlineを設定して、書き込めない時は早々に諦めて新しい接続がきたときに流れるようにしました。
とりあえず3秒としています。
ついでに再接続まわりのログを追加しています。

set websocket write deadline

---

server/binary/msg.go
server/game/msg.go
server/game/room.go
wsnet2-dotnet/WSNet2.Client/Client.cs
wsnet2-dotnet/WSNet2.Core.Test/WSNet2.Core.Test.csproj
wsnet2-unity/Assets/WSNet2/Scripts/Core/Msg/MsgPool.cs
wsnet2-unity/Assets/WSNet2/Scripts/Core/Room.cs

KickにもLeaveと同様にメッセージを渡せるようにしました。
ついでに動作確認用の `wsnet2-dotnet/WSNet2.Client` をリファクタしました。
クライアントを先に更新してからサーバを更新することで無停止で適用できます。

Kick with message

---

wsnet2-unity/Assets/WSNet2/Scripts/Core/Room.cs

see: https://github.com/KLab/wsnet2/pull/18#discussion_r1093039675

use null-condition operator

---

_doc/room.md

Add event receivers:
- OnPongReceived
- OnConnectionStateChanged
Change method arguments:
- Leave()
- Kick()

Update C# Room class document.

---

server/binary/event.go
server/binary/marshal.go
server/binary/msg.go
server/config/config.go
server/game/client.go
server/game/peer.go
server/hub/hub.go

コメントの中まで整形されるようになったようなのでgofmtをかけました

Go1.20 gofmt

---

server/game/repository.go
server/hub/hub.go
server/hub/repository.go
server/hub/service/grpc.go
server/lobby/room.go
server/log/log.go
server/pb/gameservice.proto

- gRPCのログをgameに合わせました
- gameサーバの接続情報(grpc, websockt)をlobbyからhubに渡すようにしました

Hubリファクタその1

---

server/game/client.go
server/game/interface.go
server/game/room.go
server/hub/hub.go
server/hub/repository.go

gameへの接続、送受信をclientパッケージを使う形にしました。

Hubリファクタリングその2

---

server/Makefile
server/client/connection.go
server/client/room.go
server/client/room_test.go

ClientDeadline==0は変更なしの意味でした。
Makefileのhubの依存パッケージからclientが抜けていたので加えました

fix: go client update deadline

---

server/client/connection.go

通常Msgの送信ですでにmumsg.Lock()しているので、pingとその他システムmsgもhmac使うところでmumsg.Lock()するようにしました。

hmacのHashオブジェクトを並行で触るとおかしな値になるのでLock

---

server/lobby/game_cache.go
server/lobby/hub_cache.go
server/lobby/room.go

server: GameCacheとHubCacheをlobbyのプライベートに

---

server/sql/10-schema.sql

add index (player_id) on player_log

---

server/common/enum.go
server/game/service/service.go
server/hub/service/service.go
server/lobby/game_cache.go
server/lobby/hub_cache.go

gameCache.Rand() は Running 状態のホストのみを返す。
gameCache.Get(hostID) は Closing 中のホストも返す。

lobby: graceful shutdown中のgame serverの情報を取得する

---

wsnet2-unity/Assets/WSNet2/Scripts/WSNet2Service.cs

System.ObjectとUnityEngine.Object
小文字のつもりでした。そもそもコンパイルエラーでした。すみませんでした。

コンパイルエラー修正

---

server/game/peer.go

#49 でWarnに落としてみたけれど、ログ調査中まだノイズになっているので、そもそも出さないようにしました。
明示的にcloseする過程なので、Readでエラーが起きても何もせずclientが終了するので問題は無いはずです。
また、p.closed=trueになっていないときのエラーは以前のようにErrorレベルで記録します。

peer.connを閉じたときのReadMessageのエラーがログのノイズになっているので対処

---

server/game/client.go
server/game/peer.go
server/game/service/websocket.go
wsnet2-unity/Assets/WSNet2/Scripts/Core/Connection.cs

CloseMessageを受け取った側もCloseMessageを送り返すべきでした
あわせて、サーバ側のReadエラー処理も見直しました

WebSocket切断処理修正

---

wsnet2-unity/Assets/WSNet2/Scripts/Core/Connection.cs
wsnet2-unity/Assets/WSNet2/Scripts/Core/Logger.cs

`WSNET2_LOG_DEBUG` をDefineConstantsすることでDebugビルド以外でもログが出ます

ReleaseビルドでもDebugログ出力できるようにConditional追加

---

wsnet2-unity/Assets/WSNet2/Scripts/Core/Connection.cs

並行してping送信などが動いているので、タイミング次第で退室後にエラーログが出ることがありました。

websocket close後に送信しない
