server/game/service/websocket.go, server/go.mod, server/go.sum, server/hub/service/websocket.go, server/lobby/service/api.go
gorillaプロジェクトがアーカイブしたので、 gorilla/mux から別のルーティングライブラリへの移行を検討しています。
catatsuy さんがおすすめしていたので、 go-chi への乗り換えを試してみました。
https://zenn.dev/catatsuy/articles/69222f6ce39b3a
route文字列のパターンは同じ `{変数名:正規表現}` が使えるので楽。
hostrouter あたりがちょっとだけ面倒。
=> gorilla/mux -> go-chi/chi/v5

server/cmd/wsnet2-bot/bot.go, server/game/peer.go, server/game/service/websocket.go, server/go.mod, server/go.sum, server/hub/hub.go, server/hub/repository.go, server/hub/service/websocket.go
`github.com/gorilla/websocket` が更新停止してしまったので、[時雨堂さんのfork](https://github.com/shiguredo/websocket)に置き換えました。
importしている場所多くないので直接書き換えました。
=> use github.com/shiguredo/websocket

wsnet2-dotnet/WSNet2.Core.Test/EvPongTest.cs, wsnet2-dotnet/WSNet2.Core.Test/EvResponseTest.cs, wsnet2-dotnet/WSNet2.Core.Test/SerializeTests.cs, wsnet2-unity/Assets/WSNet2/Scripts/Core/Event/EvPong.cs, wsnet2-unity/Assets/WSNet2/Scripts/Core/NetworkInformer.cs, wsnet2-unity/Assets/WSNet2/Scripts/Core/Room.cs, wsnet2-unity/Assets/WSNet2/Scripts/Core/SerialReader.cs, wsnet2-unity/Assets/WSNet2/Scripts/Core/SerialWriter.cs
EvPongでDictionaryを使い回すように修正しました。
WSNet2内部では使ってなかったBoolとULongの辞書のシリアライズが動いていなかったのであわせて修正しました。
=> EvPong refactoring

server/game/client.go
WebSocketの書き込みが詰まることが、RoomのMsgLoopにまで伝播することがあったのを修正。
`client.Removed()`は`Room.MsgLoop()`のgoroutineで呼び出されていた。
このなかで呼ぶ`peer.Close()`がwebsocket書き込み用のロック(`peer.muWrite`)を取るので
外の場所での書き込みでロックを掴んだままだとRoomのMsgLoopまで止まってしまっていた。
`peer.Close()`は呼ばれたらそのPeerが終わるだけなので、非同期で呼んだとしても問題ない
（他の送信が先に終わったらもちろん問題ないし、先にCloseしても残りは再接続してきた新しいPeerで再送される）
=> 独立goroutineでpeer.Close

wsnet2-dotnet/WSNet2.Client/Client.cs, wsnet2-unity/Assets/WSNet2/Scripts/Core/Room.cs
Pong受信でRoomの `RttMillisec`, `WatcherCount`, `LastMsgTimestamps` が更新されるので、
これらが更新されたタイミングで呼ばれるCallbackです。
補足: 更新前と全て同じ値だった場合も呼ばれます
=> Room.OnPongReceived notification

server/cmd/wsnet2-tool/cmd/oldroom.go, server/cmd/wsnet2-tool/cmd/oldrooms.go, server/cmd/wsnet2-tool/cmd/room.go, server/game/room.go, server/pb/gameservice.proto
- room
- host_idだけでなくhost名も表示
- 各playerのlast_msg_timeを表示
- gRPCのGerRoomInfoのレスポンスに追加
- interface{} -> any
- oldroom
- public/private props、player_logsが空の時エラーになっていたのを修正
- interface{} -> any
- oldrooms
- interface{} -> any
=> wsnet2-toolの強化

server/binary/marshal.go, server/binary/marshal_test.go, server/binary/unmarshal_recursive.go, server/binary/unsafe_string118.go, server/binary/unsafe_string120.go
Go1.20で加わった[unsafe.String](https://pkg.go.dev/unsafe#String)を
`unmarshalDict`のキー文字列生成に使ったところ、[20%近く高速化](https://gist.github.com/makiuchi-d/f25be9bac360bdab40aef3f662a8d4a3)できました。
もともとデータ部分は受信したメモリ領域をそのままsliceとして切り出していたので書き換えることは無く、
キー文字列も`unsafe.String`を使えばメモリコピーを避けられて高速化します。
dashboardのbackendで使っているgopherjsがGo1.18を要求するので、
1.20以前ではこれまで通りstringへのキャストをするようにしています。
=> Optimize with unsafe.String

server/Makefile, server/cmd/wsnet2-bot/main.go, server/cmd/wsnet2-game/main.go, server/cmd/wsnet2-hub/main.go, server/cmd/wsnet2-lobby/main.go, server/cmd/wsnet2-tool/cmd/root.go, server/log/log.go, server/version.go
バイナリに埋め込むバージョン番号を `git describe --tag`  で取得するようにしました。
tagが一つもないときは `v0.0.0`になりますが、OSSリリース時点のコミットに `v0.0.1` を打っておきました。
構造化ログにもバージョンを含めるようにしました。
また設定する変数を今までは各バイナリのmain.goで定義していましたが、`wsnet2.Version` に統一しました。
=> version情報をgit tagから取得、変数も統一

README.md, server/Dockerfile, server/compose-multihost.yaml, server/compose.yaml, wsnet2-dashboard/README-ja.md, wsnet2-dashboard/README.md, wsnet2-dashboard/backend/README-ja.md, wsnet2-dashboard/backend/README.md, wsnet2-dashboard/compose.yaml
- compose.yamlが推奨されているのでリネーム
- https://docs.docker.com/compose/compose-file/#compose-file
- `version`も非推奨なので削除
- ドキュメントも合わせて修正
- wait-for-it をやめ healthcheck ベースの depends_on を使うように変更
- https://github.com/KLab/wsnet2/pull/16#discussion_r1093125091
- dashboardはwait-for-itのまま
- https://github.com/superkerokero/wsnet2/pull/1#discussion_r1098222683
=> compose.yaml へのリネームと更新

server/cmd/wsnet2-tool/cmd/oldroom.go, server/cmd/wsnet2-tool/cmd/oldrooms.go, server/game/client.go, server/game/interface.go, server/game/repository.go, server/game/room.go, server/hub/repository.go, server/sql/10-schema.sql, wsnet2-dashboard/backend/src/types/models/index.ts, wsnet2-dashboard/backend/src/types/models/player_log.ts, wsnet2-dashboard/backend/src/types/models/room_history.ts, wsnet2-dashboard/frontend/src/components/RoomHistoryDataTable.vue, wsnet2-dashboard/frontend/src/store/roomHistories.ts
close: #28 
これまで`room_history`テーブルに保存していたPlayerの入室・再入室・退室のログ情報を別テーブル(`player_log`)に保存するようにしました。
加えて、peerのAttach・Detachもここに記録するようにしました。
なおhubでは記録しません。
=> player log table

server/binary/marshal.go, server/binary/unsafe_string120.go
Str8, Str16では対策していたけれど、Dictのキーが漏れていました
=> unsafe.Stringに長さ0を渡していたのを修正

server/log/log.go
unixtimeのままでは読みにくいのでRFC3339形式(小数部付き)にしました
このような形式です:
```
{"level":"info","ts":"2023-04-28T04:52:30.552917376Z","caller":"service/api.go:43","msg":"lobby api: \"tcp\" \":8080\"","host":"c8268da8b499","version":"v0.2.0-2-g76423f4"}
```
=> ファイルへのログ出力の時刻フォーマットをRFC3339形式に変更

server/Makefile
commitハッシュよりtagによるバージョン番号のほうが有用だったので
=> make build-commitをbuild-versionに変更

server/client/connection.go, server/hub/hub.go
websocket.IsCloseError()がerrorのwrapを考慮してくれなかったので、正常終了を正しく判定できていませんでした。
=> Hubが部屋終了後も接続リトライしていたのを修正

server/hub/hub.go
次のタイミングでリトライするために `nodeCountUpdated` チャネルに通知投げ込んでいるのに、
`lastNodeCount` を更新してしまっていたので、変更なしとして送信してくれないコードになってました。
=> 送信失敗したときh.lastNodeCountは更新してはいけない

wsnet2-unity/Assets/WSNet2/Scripts/Core/Connection.cs, wsnet2-unity/Assets/WSNet2/Scripts/Core/DefaultHttpClient.cs, wsnet2-unity/Assets/WSNet2/Scripts/Core/DefaultHttpClient.cs.meta, wsnet2-unity/Assets/WSNet2/Scripts/Core/WSNet2Client.cs, wsnet2-unity/Assets/WSNet2/Scripts/WSNet2Service.cs
いままで[HttpClient](https://learn.microsoft.com/ja-jp/dotnet/api/system.net.http.httpclient?view=net-7.0)を使っていましたが、Unityでは[UnityWebRequest](https://docs.unity3d.com/ja/2020.3/ScriptReference/Networking.UnityWebRequest.html)を使ったほうが良いとのことなので、
WSNet2Clientで差し替えられるようにして、UnityでWSNet2Service経由で使う時は差し替えるようにしました。
くわえて、HttpClientも毎回newしてしまっていたのを修正しました。
=> UnityではLobbyへの通信にUnityWebRequestを使う

wsnet2-unity/Assets/WSNet2/Scripts/Core/WSNet2Client.cs
サーバにリクエストを投げる間でもなくonFailedを呼びます。
Searchは配列なのでまた後で考えます。
=> 部屋番号を0にはできないのでWSNet2Clientでの指定をクライアント側でエラーにする

server/client/connection.go, server/game/service/websocket.go, server/hub/service/websocket.go, wsnet2-unity/Assets/WSNet2/Scripts/Core/Connection.cs
Unityのときだけ、Clientが部屋に居なかったときにも再接続リトライをし続けていました。
打ち切るようにしたかったのですが、HTTPのエラーかどうか判別する手段がありませんでした。[Unityでの例外生成部分](https://github.com/Unity-Technologies/corefx/blob/1011665e56d38aa482c2d596db40809f5e40064d/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs#L329)
.NETではErrorCodeがNotAWebSocketになっていて判別できていました。
ただ.NETでもレスポンスコードまでは(エラーメッセージを解析する以外では)取れなかったので、
40xは打ち切りたいけど502はリトライなどに対処できないため、
たとえ退室済みだったとしても一律でリトライするようにしました。
=> WebSocket接続するときのHTTPエラーの処理を修正

server/client/connection.go, server/hub/hub.go
接続と入室が別管理なため、入室してすぐNodeCountを送信しようとしたとき、
タイミングによってはまだ接続していないため送信がエラーになるケースがありました。
正常動作の範囲なのでログレベルを変更しました。
また別のメッセージ送信中にNodeCountを送信しようとしたときにも同様のエラーが起こり得るので、
容量付きチャネルを挟むことでこのエラーが起こりにくいようにしました。
NodeCount送信同士はintervalを挟むのでcap=1で十分なはずです。
=> HubからのNodeCount送信が極稀にエラーとして記録されていたので対処

wsnet2-unity/Assets/WSNet2/Scripts/Core/WSNet2Client.cs
互換性を維持するためRoomNotFoundを返すことにします。
部屋番号0が絶対に無いのはWSNet2側の都合(仕様)なので、利用者がそれを知らなくても自然に使えるという意図もあります。
=> 部屋番号0の検索ではRoomNotFoundExceptionを返す

wsnet2-unity/Assets/WSNet2/Scripts/DefaultUnityLogger.cs
=> UnityEngine.Debug.LogExceptionはErrorレベルのときのみ呼び出す

wsnet2-unity/Assets/WSNet2/Scripts/Core/Connection.cs
websocketの接続に成功した時点でreconnectLimitを更新してしまうため、
Upgrade直後にエラーになる場合、ClientDeadlineを超えて無駄に再接続リトライしてしまうので修正しました。
また、websocketのSendもTaskCanceledExceptionを投げうるので合わせて対策しました。
=> C#で再接続リトライをし続けてしまう問題の修正

server/game/repository.go, server/game/room.go
`player_log`テーブルの退室メッセージがすべて`Leave`だったのを、
理由に応じて `Timeout`, `Kick`, `Error` となるようにしました。
=> PlayerLogで退室理由がわかるように

_doc/wsnet2client.md, server/client/request.go, server/cmd/wsnet2-bot/cmd/root.go, server/cmd/wsnet2-bot/cmd/scenario.go, server/game/repository.go, server/game/service/grpc.go, server/lobby/api_structs.go, server/lobby/room.go, server/lobby/service/api.go, server/pb/gameservice.proto, wsnet2-unity/Assets/WSNet2/Scripts/Core/MessagePack/LobbyParams.cs, wsnet2-unity/Assets/WSNet2/Scripts/Core/WSNet2Client.cs
Client自身が現在入室中の部屋の一覧を取得できるようにしました。
- `/rooms/search/current`
- パラメータのQueryでフィルタリング（他のsearchと一緒）
- 観戦部屋は含まない
- 結果のリストは部屋の作成順に昇順ソート
実装について:
- DBだけからの取得は難しいので、各gameサーバに問い合わせています。
- 各gameサーバで直接RoomInfoを安全にコピーするには`MsgGetRoomInfo`を使わねばならないので、
gameサーバからはRoomIDのみを返し、Lobbyで集約してDBからRoomInfoを取得しています。
- DBの負荷軽減のためソートはlobbyで行っています。
=> 現在入室中の部屋一覧を取得するAPI

server/cmd/wsnet2-bot/cmd/cover_test.go, server/cmd/wsnet2-bot/cmd/root.go, server/cmd/wsnet2-bot/cmd/scenario.go
MsgClientPropと再入室のシナリオを追加しました。
go testでテストシナリオを流せるようにしました。
カバレッジをみてシナリオの網羅性を確認できます:
```sh
cd server/cmd/wsnet2-bot/cmd
docker run -d --rm \
-v `pwd`/../../../sql/10-schema.sql:/docker-entrypoint-initdb.d/10-schema.sql \
-v `pwd`/../../../sql/90-docker.sql:/docker-entrypoint-initdb.d/90-docker.sql \
-e MYSQL_ROOT_PASSWORD=root \
-e MYSQL_DATABASE=wsnet2 \
-e MYSQL_USER=wsnet2 \
-e MYSQL_PASSWORD=wsnet2pass \
-p 3306:3306 mysql:8.0
go test . -cover -coverprofile=cover.out -tags scenariocoverage \
-coverpkg=wsnet2/auth,wsnet2/binary,wsnet2/common,wsnet2/config,wsnet2/game,wsnet2/game/service,wsnet2/hub,wsnet2/hub/service,wsnet2/lobby,wsnet2/lobby/service,wsnet2/log,wsnet2/pb
go tool cover -html=cover.out -o cover.html
```
=> botにテストシナリオ追加

wsnet2-unity/Assets/WSNet2/Scripts/Core/Connection.cs
System.Net.WebSocketsではTCP_NODELAYがデフォルトfalseのままになっているため、
条件によっては余計なレイテンシが発生していました。
手元のAndroidでの計測ではNoDelayを有効にしてもWifi接続では差がありませんでしたが、
携帯回線のときにオレゴンのサーバとの通信で平均約310msから230msに有意に改善しました。
iPhoneでも同じような効果あり、元々遅い回線ほど顕著に改善がみられるようです。
WSNet2が対象としているゲームではパケット数の節約よりもレイテンシを抑えるほうが優先すべきなので、
NoDelay=true固定としたいです。
また、ClientWebSocketクラスから内部のSocketには普通にアクセすることができないので、
リフレクションを使っています。
=> TCP SocketのNoDelayを有効に

wsnet2-unity/Assets/WSNet2/Scripts/Core/Connection.cs
.NET Core以降、classの内部構造が変わっていることと、TcpNoDelayもデフォルトTrueとなっているため、
Conditional属性を使ってSetTcpNoDelay関数を呼び出さないようにしました。
（これまで.NETで利用した場合途中で警告ログだけ出して何もしない状態でした）
Unityで.NET Frameworkと.NET Standard 2.1のどちらを選んでもこの関数は正しく動くことは確認しています。
=> SetTcpNoDelay呼び差しが必要なときのみになるようにConditional設定

.github/workflows/wsnet2-dashboard.yml, server/binary/event.go, server/binary/marshal.go, server/binary/marshal_test.go, server/binary/msg.go, server/binary/unmarshal_recursive_test.go, server/cmd/wsnet2-bot/cmd/soak.go, server/cmd/wsnet2-tool/cmd/rooms.go, server/cmd/wsnet2-tool/cmd/rooms_test.go, server/lobby/prop_query_test.go
Goのシリアライザは64bit環境前提で作っていました（符号有/無の32bit intをどちらも`int`で扱っていた）
ところが、dashboardで使っているGopherjsが32bit環境をエミュレートしているため、桁溢れするときに正しく扱えていませんでした。
32bit環境でも変わらないよう、Int/UIntはint64で扱うようにして、テストも32bitで通るようにしました。
Unmarshalの結果が`interface{}`で、一部型アサーションしてる部分があり、
この書きかえがコンパイル時チェックできないので、漏れがないか注意して見てほしいです。
=> Goのシリアライザの32bit対応

wsnet2-unity/Assets/WSNet2/Scripts/Core/WSNet2Client.cs
gameサーバにWebSocketで接続前に、URLを書き換えたりできるようにしました
=> 入室した部屋の接続情報を必要に応じて調整できるように

wsnet2-dashboard/backend/Dockerfile, wsnet2-dashboard/backend/Makefile
fix: #82 
dashboardのbackendのMakefileから、serverのコード生成を呼び出せるようにしました。
コード生成に必要なgo1.22とprotocをDockerfileでインストールするようにもしてあります。
=> generate go codes on making dashboard-backend

server/client/request.go, server/cmd/wsnet2-bot/cmd/root.go, server/cmd/wsnet2-bot/cmd/scenario.go, server/game/repository.go, server/game/repository_test.go, server/game/service/websocket.go, server/go.mod, server/go.sum, server/hub/service/websocket.go, server/lobby/service/api.go, server/log/log.go
Go 1.22から、標準net/httpでもHTTPメソッドの指定とパスパラメータの抽出ができるようになりました。
今までchi（それ以前はgorilla/mux）を使ってやっていましたが、wsnet2ではそんなに高度なことはやっていないので、標準net/httpに書き換えて依存を減らしてみました。
ただ、パスパラメータ部分の正規表現マッチングはnet/httpではできないので、ハンドラ側でチェックする形に変更しました。
これによりマッチしないときのレスポンスが404から400に変わるケースがありますが、正しいクライアントならそもそも起こらないので問題ないはずです。
=> Use http.ServeMux instead of chi.Mux

server/cmd/wsnet2-bot/cmd/load.go, server/cmd/wsnet2-bot/cmd/soak.go, server/cmd/wsnet2-bot/cmd/watch.go, server/game/repository.go, server/game/repository_test.go, server/lobby/game_cache.go, server/lobby/hub_cache.go, server/lobby/room.go
go 1.22.0 で math/rand の新しいバージョンが入ったので載せ替えました。
- import を v2に変更
- IntnをIntNにリネーム
- game.Repositoryが使うrandsrcを修正
- ChaCha8よりPCGのほうが高速
- RandomHexを修正
=> Use math/rand/v2

server/cmd/wsnet2-bot/cmd/scenario.go
player1がwebsocket接続する前にplayer2が再入室してしまうと、
player1は切断メッセージを受け取れなくて、想定と異なるエラーになっていました。
（サーバ側の挙動自体は実装の想定どおりでしたが、テストシナリオの想定と異なっていました）
player1入室後にJoinedイベントを受け取ったことを確認してから再入室するようにしました。
=> fix bot: scenario rejoin
